spark.master                     spark://spark-master:7077
spark.eventLog.enabled           true
spark.eventLog.dir               hdfs://namenode:9000/spark-events
spark.history.fs.logDirectory    hdfs://namenode:9000/spark-events
spark.sql.warehouse.dir          hdfs://namenode:9000/user/hive/warehouse
spark.hadoop.fs.defaultFS        hdfs://namenode:9000
spark.sql.shuffle.partitions     8
spark.driver.memory              1g
spark.executor.memory            1g
